### ISSUE TITLE
Add favicon, Title and Meta Tags

### ISSUE THREAD

**Issue by ZenVega** [ZenVega/unter_der_hand#4]
Let's make that page social media ready. We need favicons and a proper title, so it doesn't get displayed like this anymore: 
<img width="230" alt="image" src="https://github.com/ZenVega/unter_der_hand/assets/50147356/80d92d03-be67-420b-802e-20e72a821105">
Further, let's add the meta tags to properly display it as shared content. Here is a nice guide for that: 
https://css-tricks.com/essential-meta-tags-social-media/

While debugging and checking on your messengers on your phone, it can be a little finicky to clear the cache of these apps and be careful, that it doesn't include deleting all the downloaded images

**Comment by ZenVega** [comment]
To add the meta tags you could absolutely just include them in your intex.js as html-tags, however Next.js has quite an slick way to include meta tags in your HTML: https://nextjs.org/docs/app/building-your-application/optimizing/metadata .

**Comment by MaximilianRaine** [comment]
fixed in #11
